### ISSUE TITLE
Metadata parameters

### ISSUE THREAD

**Issue by andrekutianski** [WHMCS/sample-merchant-gateway#1]
The wiki page http://docs.whmcs.com/Gateway_Module_Meta_Data_Parameters don't have any information about additional metadata parameters.

**Comment by itskawsar** [comment]
Following page too: http://docs.whmcs.com/Gateway_Module_Meta_Data_Parameters :(

**Comment by JFernandoGomez** [comment]
=/ +1

**Comment by mattpugh** [comment]
I believe this page has the information you are looking for: https://developers.whmcs.com/payment-gateways/meta-data-params/
