### ISSUE TITLE
Parse error: syntax error, unexpected 

### ISSUE THREAD

**Issue by VasquezSRE** [WHMCS/sample-merchant-gateway#4]
( ! ) Parse error: syntax error, unexpected ';', expecting ')' in WHMCSDIR/modules/gateways/merchantgateway.php on line 207

    $postfields = array(
        'account_id' => $accountId,
        'invoice_id' => $invoiceId,
        'amount' => $amount,
        'currency' => $currencyCode,
        'card_type' => $cardType,
        'card_number' => $cardNumber,
        'card_expiry_month' => substr($cardExpiry, 0, 2),
        'card_expiry_year' => substr($cardExpiry, 2, 2),
        'card_cvv' => $cardCvv,
        'card_holder_name' => $firstname . ' ' . $lastname,
        'card_holder_address' => $address1,
        'card_holder_city' => $city,
        'card_holder_state' => $state,
        'card_holder_zip' => $postcode,
        'card_holder_country' => $country,
        'return_url' => $systemUrl . '/modules/gateways/callback/' . $moduleName . '.php', <= this line
    );

**Comment by JFernandoGomez** [comment]
+1

**Comment by mattpugh** [comment]
This has been fixed by PR #5
