### ISSUE TITLE
Possible typo?

### ISSUE THREAD

**Issue by SparK-Cruz** [WHMCS/sample-merchant-gateway#8]
https://github.com/WHMCS/sample-merchant-gateway/blob/de17ca61749ee9747e0beae0987d340c38c41e7f/modules/gateways/merchantgateway.php#L43

Is it supposed to be `DisableLocalCredtCardInput` or `DisableLocalCreditCardInput`?

**Comment by mattpugh** [comment]
You are absolutely correct. Submitting a fix for this now.

**Comment by PeaStew** [comment]
Still there 3 years later

**Comment by mattpugh** [comment]
Erm, it's not - commit e2df0b0 fixed it. The line has since been removed however since we now have a sample token module which demonstrates its use instead.

**Comment by PeaStew** [comment]
It is broken in the other sample module. Which I raised a new PR for, got wires crossed because of the similar names for both the modules.

https://github.com/WHMCS/sample-gateway-module/pull/12
